use_frameworks!

target 'SQLiteManager_Example' do
  pod 'SQLiteManager', :path => '../'

  target 'SQLiteManager_Tests' do
    inherit! :search_paths

end
end

target 'SQLiteManager_TV_Example' do
	pod 'SQLiteManager', :path => '../'
	
	target 'SQLiteManager_TV_ExampleTests' do
		inherit! :search_paths
		
	end
end
