# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
podfile: Example/
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/SQLiteManager.xcworkspace | -scheme SQLiteManager-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO && -scheme SQLiteManager_TV_Example -sdk appletvos9.2 ONLY_ACTIVE_ARCH=NO | xcpretty
