# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode11.2
podfile: Example/
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild  -workspace Example/SQLiteManager.xcworkspace -scheme SQLiteManager_Example -destination 'platform=iOS Simulator,name=iPhone 8' test | xcpretty && xcodebuild  -workspace Example/SQLiteManager.xcworkspace -scheme SQLiteManager_TV_Example -destination 'platform=tvOS Simulator,name=Apple TV' test | xcpretty
